FROM ubuntu:latest

WORKDIR /app

RUN apt-get update && \
    apt-get install -y wget && \
    apt-get install -y tzdata

RUN wget https://github.com/SCH-Discord/NoticeNotifier/releases/latest/download/NoticeNotifier

RUN chmod +x NoticeNotifier

ENV TZ=Asia/Seoul

ENTRYPOINT ["./NoticeNotifier"]