FROM eclipse-temurin:17-jre

WORKDIR /app

RUN apt-get update && \
    apt-get install -y wget

RUN wget https://github.com/SCH-Discord/Web/releases/latest/download/SCH_Discord.jar

ENTRYPOINT ["java", "-jar", "SCH_Discord.jar"]