version: "3.0"

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    environment:
      - TZ=Asia/Seoul
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=${DB_NAME}
    ports:
      - "3306:3306"

  web:
    image: eclipse-temurin:17-jre
    container_name: Web
    working_dir: /app
    volumes:
      - ./web/build/libs:/app
    environment:
      - TZ=Asia/Seoul
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    command: [ "java", "-jar", "SCH_Discord.jar" ]
    depends_on:
        - mariadb
    ports:
        - "8080:8080"

  notifier:
    image: golang:latest
    container_name: NoticeNotifier
    working_dir: /app
    environment:
      - TZ=Asia/Seoul
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    volumes:
      - ./NoticeNotifier:/app
    command: ["go", "run", "main.go"]
    depends_on:
      - mariadb